---
exclude_paths:
 - "/vendor/*"
 - "/phinx/*"
engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
  phan:
    enabled: true
    config:
      file_extensions: "php"
  phpmd:
    enabled: true
    checks:
      UnusedFormalParameter:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.php"